<li class="headerItem">
    <i class="far fa-heart"></i>
    <small>Wish list</small>
</li>

<li class="headerItem">
    <i class="fas fa-user-alt"></i>
    <small>Log in</small>
</li>

<li class="headerItem">
    <i class="fas fa-map-marker-alt"></i>
    <small><a href="">Find an airport store</a></small>
</li>

<li class="headerItem">
    <i class="fas fa-phone"></i>
    <small>Contact us</small>
</li>