<?php if ($this->getFaqCategoriesList()): ?>
    <div class="block block-faq-category">
        <div class="block-title">
            <strong><a href="../faqs.html"><?php echo __('All FAQs'); ?></a></strong>
        </div>
        <div class="block-content">
            <ol class="items">
                <?php foreach($this->getFaqCategoriesList() as $fclist): ?>
                    <li class="item">
                        <a href="<?php echo $this->getFaqCategoryFullPath($fclist['identifier']); ?>">
                            <?php echo __($fclist['title']); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
