<div class="faq-category">
    <?php if ($this->getFrequentlyAskedQuestion()): ?>
        <ol class="items faqs-list">
            <?php foreach($this->getFrequentlyAskedQuestion() as $faq): ?>
                <li class="item" id="faq-id-<?php echo $faq['faq_id']; ?>">
                    <a href="<?php echo $this->getFaqFullPath($faq['identifier']); ?>"><span class="faq-iconplus"></span><?php echo $faq['title']; ?></a>
                    <div class="description" id="description">
                        <?php echo $block->filterProvider($faq['content']); ?>
                    </div>
                    <div class="read-more"><?php echo __('Read more'); ?></div>
                </li>
            <?php endforeach; ?>
        </ol>
    <?php else: ?>
        <ol class="items faqs-list">
            <li class="item no-question">
                <a href="#"><?php echo __('There are no frequently asked questions was found.'); ?></a>
            </li>
        </ol>
    <?php endif; ?>

    <?php if ($this->getLastestFAQ()): ?>
        <ol class="items faqs-list">
            <?php foreach($this->getLastestFAQ() as $faq): ?>
                <li class="item" id="faq-id-<?php echo $faq['faq_id']; ?>">
                    <a href="<?php echo $this->getFaqFullPath($faq['identifier']); ?>"><span class="faq-iconplus"></span><?php echo $faq['title']; ?></a>
                    <div class="description" id="description">
                        <?php echo $block->filterProvider($faq['content']); ?>
                    </div>
                    <div class="read-more"><?php echo __('Read more'); ?></div>
                </li>
            <?php endforeach; ?>
        </ol>
    <?php else: ?>
        <ol class="items faqs-list">
            <li class="item no-question">
                <a href="#"><?php echo __('There are no latest questions was found.'); ?></a>
            </li>
        </ol>
    <?php endif; ?>
</div>


