<div class="socialIcons">
    <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?= $block->getProduct()->getProductUrl(); ?>" class="socialButton">
        <i class="fab fa-facebook-f"></i>
    </a>
    <a target="_blank" href="https://twitter.com/home?status=<?= $block->getProduct()->getProductUrl(); ?>" class="socialButton">
        <i class="fab fa-twitter"></i>
    </a>
    <a target="_blank" href="https://pinterest.com/pin/create/button/?url=<?= $block->getProduct()->getProductUrl(); ?>&media=&description=" class="socialButton">
        <i class="fab fa-pinterest-p"></i>
    </a>
</div>