<?php
/**
 * @copyright Daniel Coull <d.coull@suttonsilver.co.uk>
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<div class="form-row">
  <form class="form contact"
        action="<?= $block->escapeUrl($block->getFormAction()) ?>"
        id="contact-form"
        method="post"
        data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
        data-mage-init='{"validation":{}}'>
      <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Message Us')) ?></span></legend><br />
          <div class="flex-inline">
            <div class="field first_name required">
                  <label class="label" for="name"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
                  <div class="control">
                      <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                  </div>
              </div>
            <div class="field last_name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
                <div class="control">
                  <input name="last_name" id="name" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('last_name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
              </div>
          </div>
          <div class="field email required">
              <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
              <div class="control">
                  <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
              </div>
          </div>
          <div class="field telephone">
              <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
              <div class="control">
                  <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
              </div>
          </div>
          <div class="field orderno">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Order Number')) ?></span></label>
            <div class="control">
              <input name="orderno" id="orderno" title="<?= $block->escapeHtmlAttr(__('Order Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('orderno')) ?>" class="input-text" type="text" />
            </div>
          </div>
          <div class="field question">
            <label class="label" for="question"><span><?= $block->escapeHtml(__('My Question')) ?></span></label>
            <div class="control">
              <select name="myquestion" id="myquestion" title="<?= $block->escapeHtmlAttr(__('My Question')) ?>">
                <option value="general"><?= $block->escapeHtml(__('General Information')); ?></option>
                <option value="payments"><?= $block->escapeHtml(__('Payments')); ?></option>
                <option value="returns"><?= $block->escapeHtml(__('Returns')); ?></option>
              </select>
            </div>
          </div>
          <div class="field comment required">
              <label class="label" for="comment"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
              <div class="control">
                  <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
              </div>
          </div>
          <?= $block->getChildHtml('form.additional.info') ?>
      </fieldset>
      <div class="actions-toolbar">
          <div class="primary">
              <input type="hidden" name="hideit" id="hideit" value="" />
              <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                  <span><?= $block->escapeHtml(__('Submit')) ?></span>
              </button>
          </div>
      </div>
  </form>
    <div class="socialIcons">
        <h4>Social</h4>
        <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?= $block->getUrl(); ?>" class="socialButton">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a target="_blank" href="https://twitter.com/home?status=<?= $block->getUrl(); ?>" class="socialButton">
            <i class="fab fa-twitter"></i>
        </a>
        <a target="_blank" href="https://pinterest.com/pin/create/button/?url=<?= $block->getUrl(); ?>&media=&description=" class="socialButton">
            <i class="fab fa-pinterest-p"></i>
        </a>
    </div>
</div>